version: '3'

services:
 postgres:
   image: postgres
   environment:
     POSTGRES_DB: postgres
     POSTGRES_USER: postgres
     POSTGRES_PASSWORD: default
   volumes:
     - ./store/migration/initial.up.sql:/docker-entrypoint-initdb.d/1_initialize_schema.up.sql
    #  - ./store/testdata.sql:/docker-entrypoint-initdb.d/testdata.sql
   ports:
     - 5432:5432
  # pgadmin:
  #     container_name: pgadmin_container
  #     image: dpage/pgadmin4
  #     environment:
  #       PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
  #       PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
  #       PGADMIN_CONFIG_SERVER_MODE: 'False'
  #     ports:
  #     - "${PGADMIN_PORT:-5050}:80"

